import AuthServices from "@repo/services/auth";
import OauthService from "@repo/services/oAuth";
import FormServices from "@repo/services/form";
import FormBuilderAgentServices from "@repo/services/agent/formBuilderAgent";
import FormRespondentAgentService from "@repo/services/agent/formRespondentAgent";
import EmailServices from "@repo/services/email";
import PollService from "@repo/services/poll";
import TagService from "@repo/services/tag";
import PetitionService from "@repo/services/petition";
import UploadService from "@repo/services/upload";
import QuizService from "@repo/services/quiz";
import LangChainService from "@repo/services/agent/quizBuilderAgent/langchain";
import QuizBuilderAgentService from "@repo/services/agent/quizBuilderAgent";
import ExploreService from "@repo/services/explore";
import SubscriptionService from "@repo/services/razorpay";
export const authService = new AuthServices();
export const oAuthService = new OauthService();
export const formServices = new FormServices();
export const formBuilderAgentServices = new FormBuilderAgentServices();
export const formRespondentAgentService = new FormRespondentAgentService();
export const emailServices = new EmailServices();
export const pollService = new PollService();
export const tagService = new TagService();
export const petitionService = new PetitionService();
export const uploadService = new UploadService();
export const quizService = new QuizService();
export const langChainService = new LangChainService();
export const quizBuilderAgentService = new QuizBuilderAgentService();
export const exploreService = new ExploreService();
export const subscriptionService = new SubscriptionService();
